# Generated by Django 5.0.3 on 2024-03-28 21:54

import social_meddia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_meddia', '0003_remove_post_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=social_meddia.models.get_image_filename),
        ),
    ]
